### PR TITLE
fix: #268: disable slider for empty balances

### LINKED ISSUE #268: Market order form slider stops working if a subaccount is selected
The slider works correctly when I select the `Main account`, but stops effecting the form entries ("Sell", "Receive") when I select any other account, regardless of whether it has a sufficient balance or not. This seems related to #243.

Screenshot 2025-01-14 at 2 55 36 PM

Screenshot 2025-01-14 at 2 55 50 PM

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #268 

- Disables the Slider if the balance of controlled asset is empty. Tried removing Slider but disabling is better UI
- For 'Sell' tab, uses base asset instead of quote asset

image

### CODE REVIEW

File: src/pages/trade/ui/order-form/order-form-market.tsx [hunk 1]
```diff
@@ -82,8 +83,8 @@ export const MarketOrderForm = observer(({ parentStore }: { parentStore: OrderFo
         />
       </div>
       <Slider
-        inputValue={store.quoteInput}
-        balance={store.quoteBalance}
+        inputValue={isBuy ? store.quoteInput : store.baseInput}
```
Comment (erwanor) [inline src/pages/trade/ui/order-form/order-form-market.tsx:86]: ACK, lgtm

**Review by erwanor — APPROVED** [review]
