### PR TITLE
fix: #316: improve pair selector UX

### LINKED ISSUE #316: Pair selector should prefill quote asset
Users generally want to use only one quote asset, but the current pair selector makes them re-input it every time. This should be fixed by pre-filling the quote asset.

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #316 

General improvements to the PairSelector component:
1. Both base and quote assets are prefilled when opening the pair selector, so users won't have to reselect assets from scratch
2. When searching for an asset and selecting it, the main screen will now appear again with confirmation button
3. Scroll restores to the top after selecting assets, so users don't get confused

### CODE REVIEW

File: src/pages/trade/model/use-path.ts [hunk 1]
```diff
@@ -21,15 +21,12 @@ export const usePathToMetadata = () => {
...
-  const quoteSymbolNormalized = quoteSymbol.toUpperCase();
-
   const query = useQuery({
     queryKey: ['pathToMetadata', data, baseSymbol, quoteSymbol],
     queryFn: () => {
       return {
-        baseAsset: data?.find(m => m.symbol === baseSymbolNormalized),
-        quoteAsset: data?.find(a => a.symbol === quoteSymbolNormalized),
+        baseAsset: data?.find(m => m.symbol.toLowerCase() === baseSymbol.toLowerCase()),
+        quoteAsset: data?.find(a => a.symbol.toLowerCase() === quoteSymbol.toLowerCase()),
```
Comment (VanishMax) [inline src/pages/trade/model/use-path.ts:29]: this fix enabled symbols like `TestUSD` that weren't previously matched by uppercase

**Review by JasonMHasperhoven — APPROVED** [review]
