### PR TITLE
api(book): fix sell side calculation

### LINKED ISSUE #285: Route book amount is rendering the price rather than amount
I open to sell 1 UM at 0.856

Image

The price is correctly rendered, but the amount should be the base amount:

Image

### PR DESCRIPTION
**Pull request by erwanor**
This fix #285, and simplifies the route book construction logic.

### CODE REVIEW

File: src/shared/api/server/book/helpers.ts [hunk 1]
```diff
@@ -38,10 +38,17 @@ export const getValueView = (registry: Registry, { amount, assetId }: Value) =>
...
 ): Trace => {
-  const baseValue = trace.value[0];
-  const quoteValue = trace.value[trace.value.length - 1];
+  // First, we record the first and last hops.
+  const firstHop = trace.value[0];
+  const lastHop = trace.value[trace.value.length - 1];
+
+  // Then, we determine which is the base and quote asset.
+  // If we are selling, the first hop is the base asset, the last hop is the quote asset.
+  // Vice-versa for buying, the first hop is the quote asset, the last hop is the base asset.
```
Comment (TalDerei) [inline src/shared/api/server/book/helpers.ts:49]: issue: this comment is contradictory to the code logic

**Review by TalDerei — APPROVED** [review]
price calculation is easier to understand than the previous `invertPrice` condition, and seems to be working properly. minor issue with the comment that needs fixing

--------------

Screenshot 2025-01-16 at 9 23 40 PM

Screenshot 2025-01-16 at 9 24 00 PM

File: src/shared/api/server/book/helpers.ts (hunk 1 above)
Comment (TalDerei) [reply src/shared/api/server/book/helpers.ts:49]: selling: "last hop is the base asset, and the first hop is the quote asset"
buying: "first hop is the base asset, and the last hop is the quote asset"

Comment (erwanor) [reply src/shared/api/server/book/helpers.ts]: Thanks, I added comments to clarify and reworked the logic some more to clarify.
