### PR TITLE
fix: reload on wallet disconnect

### LINKED ISSUE #157: Post-disconnect asset list persisting
Steps to reproduce:
1. Connect wallet that has a balance
2. Click asset selector and note token balances
3. Disconnect wallet
4. Click asset selector tab and the previous connected wallet's balances persist (refreshing fixes it)

Very likely a mobx store not re-rendering after the connection state changes

Example after disconnecting:
Screenshot 2024-11-22 at 4 42 57 PM

### PR DESCRIPTION
**Pull request by vacekj**
fixes #157 by reloading on wallet disconnect

### CODE REVIEW

File: src/shared/model/connection/index.ts [hunk 1]
```diff
@@ -83,6 +83,7 @@ class ConnectionStateStore {
 
     try {
       await penumbra.disconnect();
+      window.location.reload();
```
Comment (TalDerei) [inline src/shared/model/connection/index.ts:86]: suggestion: we want to ensure the page reload is handled in the `finally` block, independent of whether the disconnection succeeds or fails.

```ts
    try {
      await penumbra.disconnect();
    } catch (error) {
      console.error("Error during disconnect:", error);
    } finally {
      window.location.reload();
    }
```

consider for instance when the extension's connection context becomes invalidated, resulting in an unsuccessful disconnection.

https://github.com/user-attachments/assets/7f846f0e-2df3-467d-bfe2-ae6444c20812

**Review by TalDerei — CHANGES_REQUESTED** [review]
minor nit

File: src/shared/model/connection/index.ts (hunk 1 above)
Comment (vacekj) [reply src/shared/model/connection/index.ts:86]: Good point, fixed.

**Review by TalDerei — APPROVED** [review]
